# Generated by Django 4.0.5 on 2022-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
